component_depth: 1
languages:
- java
exclude:
- ./analysis/.*
- ./analysis/common/.*
- ./analysis/icu/.*
- ./analysis/kuromoji/.*
- ./analysis/morfologik/.*
- ./analysis/phonetic/.*
- ./analysis/smartcn/.*
- ./analysis/stempel/.*
- ./analysis/uima/.*
- ./backwards/.*
- ./benchmark/.*
- ./benchmark/conf/.*
- ./benchmark/scripts/.*
- ./bin/.*
- ./bin/conf/.*
- ./bin/org/.*
- ./bin/org/apache/.*
- ./bin/org/apache/lucene/.*
- ./bin/org/apache/lucene/analysis/.*
- ./bin/org/apache/lucene/analysis/ar/.*
- ./bin/org/apache/lucene/analysis/bg/.*
- ./bin/org/apache/lucene/analysis/br/.*
- ./bin/org/apache/lucene/analysis/ca/.*
- ./bin/org/apache/lucene/analysis/charfilter/.*
- ./bin/org/apache/lucene/analysis/cjk/.*
- ./bin/org/apache/lucene/analysis/cn/.*
- ./bin/org/apache/lucene/analysis/cn/smart/.*
- ./bin/org/apache/lucene/analysis/cn/smart/hhmm/.*
- ./bin/org/apache/lucene/analysis/commongrams/.*
- ./bin/org/apache/lucene/analysis/compound/.*
- ./bin/org/apache/lucene/analysis/compound/hyphenation/.*
- ./bin/org/apache/lucene/analysis/core/.*
- ./bin/org/apache/lucene/analysis/cz/.*
- ./bin/org/apache/lucene/analysis/da/.*
- ./bin/org/apache/lucene/analysis/de/.*
- ./bin/org/apache/lucene/analysis/el/.*
- ./bin/org/apache/lucene/analysis/en/.*
- ./bin/org/apache/lucene/analysis/es/.*
- ./bin/org/apache/lucene/analysis/eu/.*
- ./bin/org/apache/lucene/analysis/fa/.*
- ./bin/org/apache/lucene/analysis/fi/.*
- ./bin/org/apache/lucene/analysis/fr/.*
- ./bin/org/apache/lucene/analysis/ga/.*
- ./bin/org/apache/lucene/analysis/gl/.*
- ./bin/org/apache/lucene/analysis/hi/.*
- ./bin/org/apache/lucene/analysis/hu/.*
- ./bin/org/apache/lucene/analysis/hunspell/.*
- ./bin/org/apache/lucene/analysis/hy/.*
- ./bin/org/apache/lucene/analysis/icu/.*
- ./bin/org/apache/lucene/analysis/icu/segmentation/.*
- ./bin/org/apache/lucene/analysis/icu/tokenattributes/.*
- ./bin/org/apache/lucene/analysis/id/.*
- ./bin/org/apache/lucene/analysis/in/.*
- ./bin/org/apache/lucene/analysis/it/.*
- ./bin/org/apache/lucene/analysis/ja/.*
- ./bin/org/apache/lucene/analysis/ja/dict/.*
- ./bin/org/apache/lucene/analysis/ja/tokenattributes/.*
- ./bin/org/apache/lucene/analysis/ja/util/.*
- ./bin/org/apache/lucene/analysis/lv/.*
- ./bin/org/apache/lucene/analysis/miscellaneous/.*
- ./bin/org/apache/lucene/analysis/morfologik/.*
- ./bin/org/apache/lucene/analysis/ngram/.*
- ./bin/org/apache/lucene/analysis/nl/.*
- ./bin/org/apache/lucene/analysis/no/.*
- ./bin/org/apache/lucene/analysis/path/.*
- ./bin/org/apache/lucene/analysis/pattern/.*
- ./bin/org/apache/lucene/analysis/payloads/.*
- ./bin/org/apache/lucene/analysis/phonetic/.*
- ./bin/org/apache/lucene/analysis/pl/.*
- ./bin/org/apache/lucene/analysis/position/.*
- ./bin/org/apache/lucene/analysis/pt/.*
- ./bin/org/apache/lucene/analysis/query/.*
- ./bin/org/apache/lucene/analysis/reverse/.*
- ./bin/org/apache/lucene/analysis/ro/.*
- ./bin/org/apache/lucene/analysis/ru/.*
- ./bin/org/apache/lucene/analysis/shingle/.*
- ./bin/org/apache/lucene/analysis/sinks/.*
- ./bin/org/apache/lucene/analysis/snowball/.*
- ./bin/org/apache/lucene/analysis/standard/.*
- ./bin/org/apache/lucene/analysis/standard/std31/.*
- ./bin/org/apache/lucene/analysis/standard/std34/.*
- ./bin/org/apache/lucene/analysis/standard/std36/.*
- ./bin/org/apache/lucene/analysis/stempel/.*
- ./bin/org/apache/lucene/analysis/sv/.*
- ./bin/org/apache/lucene/analysis/synonym/.*
- ./bin/org/apache/lucene/analysis/th/.*
- ./bin/org/apache/lucene/analysis/tokenattributes/.*
- ./bin/org/apache/lucene/analysis/tr/.*
- ./bin/org/apache/lucene/analysis/uima/.*
- ./bin/org/apache/lucene/analysis/uima/ae/.*
- ./bin/org/apache/lucene/analysis/uima/an/.*
- ./bin/org/apache/lucene/analysis/util/.*
- ./bin/org/apache/lucene/analysis/wikipedia/.*
- ./bin/org/apache/lucene/benchmark/.*
- ./bin/org/apache/lucene/benchmark/byTask/.*
- ./bin/org/apache/lucene/benchmark/byTask/feeds/.*
- ./bin/org/apache/lucene/benchmark/byTask/programmatic/.*
- ./bin/org/apache/lucene/benchmark/byTask/stats/.*
- ./bin/org/apache/lucene/benchmark/byTask/tasks/.*
- ./bin/org/apache/lucene/benchmark/byTask/tasks/alt/.*
- ./bin/org/apache/lucene/benchmark/byTask/utils/.*
- ./bin/org/apache/lucene/benchmark/quality/.*
- ./bin/org/apache/lucene/benchmark/quality/trec/.*
- ./bin/org/apache/lucene/benchmark/quality/utils/.*
- ./bin/org/apache/lucene/benchmark/utils/.*
- ./bin/org/apache/lucene/classification/.*
- ./bin/org/apache/lucene/classification/utils/.*
- ./bin/org/apache/lucene/codecs/.*
- ./bin/org/apache/lucene/codecs/appending/.*
- ./bin/org/apache/lucene/codecs/asserting/.*
- ./bin/org/apache/lucene/codecs/blockterms/.*
- ./bin/org/apache/lucene/codecs/bloom/.*
- ./bin/org/apache/lucene/codecs/cheapbastard/.*
- ./bin/org/apache/lucene/codecs/compressing/.*
- ./bin/org/apache/lucene/codecs/compressing/dummy/.*
- ./bin/org/apache/lucene/codecs/diskdv/.*
- ./bin/org/apache/lucene/codecs/intblock/.*
- ./bin/org/apache/lucene/codecs/lucene3x/.*
- ./bin/org/apache/lucene/codecs/lucene40/.*
- ./bin/org/apache/lucene/codecs/lucene41/.*
- ./bin/org/apache/lucene/codecs/lucene41ords/.*
- ./bin/org/apache/lucene/codecs/lucene42/.*
- ./bin/org/apache/lucene/codecs/memory/.*
- ./bin/org/apache/lucene/codecs/mockintblock/.*
- ./bin/org/apache/lucene/codecs/mockrandom/.*
- ./bin/org/apache/lucene/codecs/mocksep/.*
- ./bin/org/apache/lucene/codecs/nestedpulsing/.*
- ./bin/org/apache/lucene/codecs/perfield/.*
- ./bin/org/apache/lucene/codecs/pulsing/.*
- ./bin/org/apache/lucene/codecs/ramonly/.*
- ./bin/org/apache/lucene/codecs/sep/.*
- ./bin/org/apache/lucene/codecs/simpletext/.*
- ./bin/org/apache/lucene/collation/.*
- ./bin/org/apache/lucene/collation/tokenattributes/.*
- ./bin/org/apache/lucene/demo/.*
- ./bin/org/apache/lucene/demo/facet/.*
- ./bin/org/apache/lucene/demo/test-files/.*
- ./bin/org/apache/lucene/demo/test-files/docs/.*
- ./bin/org/apache/lucene/demo/xmlparser/.*
- ./bin/org/apache/lucene/document/.*
- ./bin/org/apache/lucene/facet/.*
- ./bin/org/apache/lucene/facet/associations/.*
- ./bin/org/apache/lucene/facet/codecs/.*
- ./bin/org/apache/lucene/facet/codecs/facet42/.*
- ./bin/org/apache/lucene/facet/collections/.*
- ./bin/org/apache/lucene/facet/complements/.*
- ./bin/org/apache/lucene/facet/doc-files/.*
- ./bin/org/apache/lucene/facet/encoding/.*
- ./bin/org/apache/lucene/facet/index/.*
- ./bin/org/apache/lucene/facet/params/.*
- ./bin/org/apache/lucene/facet/partitions/.*
- ./bin/org/apache/lucene/facet/sampling/.*
- ./bin/org/apache/lucene/facet/search/.*
- ./bin/org/apache/lucene/facet/taxonomy/.*
- ./bin/org/apache/lucene/facet/taxonomy/directory/.*
- ./bin/org/apache/lucene/facet/taxonomy/writercache/.*
- ./bin/org/apache/lucene/facet/taxonomy/writercache/cl2o/.*
- ./bin/org/apache/lucene/facet/taxonomy/writercache/lru/.*
- ./bin/org/apache/lucene/facet/util/.*
- ./bin/org/apache/lucene/index/.*
- ./bin/org/apache/lucene/index/memory/.*
- ./bin/org/apache/lucene/misc/.*
- ./bin/org/apache/lucene/misc/doc-files/.*
- ./bin/org/apache/lucene/queries/.*
- ./bin/org/apache/lucene/queries/function/.*
- ./bin/org/apache/lucene/queries/function/docvalues/.*
- ./bin/org/apache/lucene/queries/mlt/.*
- ./bin/org/apache/lucene/queryparser/.*
- ./bin/org/apache/lucene/queryparser/analyzing/.*
- ./bin/org/apache/lucene/queryparser/classic/.*
- ./bin/org/apache/lucene/queryparser/complexPhrase/.*
- ./bin/org/apache/lucene/queryparser/ext/.*
- ./bin/org/apache/lucene/queryparser/flexible/.*
- ./bin/org/apache/lucene/queryparser/flexible/core/.*
- ./bin/org/apache/lucene/queryparser/flexible/core/builders/.*
- ./bin/org/apache/lucene/queryparser/flexible/core/config/.*
- ./bin/org/apache/lucene/queryparser/flexible/core/messages/.*
- ./bin/org/apache/lucene/queryparser/flexible/core/nodes/.*
- ./bin/org/apache/lucene/queryparser/flexible/core/parser/.*
- ./bin/org/apache/lucene/queryparser/flexible/core/processors/.*
- ./bin/org/apache/lucene/queryparser/flexible/core/util/.*
- ./bin/org/apache/lucene/queryparser/flexible/messages/.*
- ./bin/org/apache/lucene/queryparser/flexible/precedence/.*
- ./bin/org/apache/lucene/queryparser/flexible/precedence/processors/.*
- ./bin/org/apache/lucene/queryparser/flexible/spans/.*
- ./bin/org/apache/lucene/queryparser/flexible/standard/.*
- ./bin/org/apache/lucene/queryparser/flexible/standard/builders/.*
- ./bin/org/apache/lucene/queryparser/flexible/standard/config/.*
- ./bin/org/apache/lucene/queryparser/flexible/standard/nodes/.*
- ./bin/org/apache/lucene/queryparser/flexible/standard/parser/.*
- ./bin/org/apache/lucene/queryparser/flexible/standard/processors/.*
- ./bin/org/apache/lucene/queryparser/surround/.*
- ./bin/org/apache/lucene/queryparser/surround/parser/.*
- ./bin/org/apache/lucene/queryparser/surround/query/.*
- ./bin/org/apache/lucene/queryparser/util/.*
- ./bin/org/apache/lucene/queryparser/xml/.*
- ./bin/org/apache/lucene/queryparser/xml/builders/.*
- ./bin/org/apache/lucene/sandbox/.*
- ./bin/org/apache/lucene/sandbox/queries/.*
- ./bin/org/apache/lucene/sandbox/queries/regex/.*
- ./bin/org/apache/lucene/search/.*
- ./bin/org/apache/lucene/search/doc-files/.*
- ./bin/org/apache/lucene/search/grouping/.*
- ./bin/org/apache/lucene/search/grouping/function/.*
- ./bin/org/apache/lucene/search/grouping/term/.*
- ./bin/org/apache/lucene/search/highlight/.*
- ./bin/org/apache/lucene/search/highlight/custom/.*
- ./bin/org/apache/lucene/search/join/.*
- ./bin/org/apache/lucene/search/payloads/.*
- ./bin/org/apache/lucene/search/postingshighlight/.*
- ./bin/org/apache/lucene/search/similarities/.*
- ./bin/org/apache/lucene/search/spans/.*
- ./bin/org/apache/lucene/search/spell/.*
- ./bin/org/apache/lucene/search/suggest/.*
- ./bin/org/apache/lucene/search/suggest/analyzing/.*
- ./bin/org/apache/lucene/search/suggest/fst/.*
- ./bin/org/apache/lucene/search/suggest/jaspell/.*
- ./bin/org/apache/lucene/search/suggest/tst/.*
- ./bin/org/apache/lucene/search/vectorhighlight/.*
- ./bin/org/apache/lucene/spatial/.*
- ./bin/org/apache/lucene/spatial/prefix/.*
- ./bin/org/apache/lucene/spatial/prefix/tree/.*
- ./bin/org/apache/lucene/spatial/query/.*
- ./bin/org/apache/lucene/spatial/util/.*
- ./bin/org/apache/lucene/spatial/vector/.*
- ./bin/org/apache/lucene/store/.*
- ./bin/org/apache/lucene/util/.*
- ./bin/org/apache/lucene/util/automaton/.*
- ./bin/org/apache/lucene/util/fst/.*
- ./bin/org/apache/lucene/util/junitcompat/.*
- ./bin/org/apache/lucene/util/mutable/.*
- ./bin/org/apache/lucene/util/packed/.*
- ./bin/org/apache/lucene/validation/.*
- ./bin/org/egothor/.*
- ./bin/org/egothor/stemmer/.*
- ./bin/org/tartarus/.*
- ./bin/org/tartarus/snowball/.*
- ./bin/org/tartarus/snowball/ext/.*
- ./classification/.*
- ./codecs/.*
- ./core/.*
- ./demo/.*
- ./docs/.*
- ./docs/changes/.*
- ./facet/.*
- ./grouping/.*
- ./highlighter/.*
- ./join/.*
- ./lib/.*
- ./licenses/.*
- ./memory/.*
- ./misc/.*
- ./queries/.*
- ./queryparser/.*
- ./queryparser/docs/.*
- ./queryparser/docs/flexible/.*
- ./queryparser/docs/surround/.*
- ./queryparser/docs/xml/.*
- ./queryparser/docs/xml/img/.*
- ./sandbox/.*
- ./site/.*
- ./site/changes/.*
- ./site/html/.*
- ./site/xsl/.*
- ./spatial/.*
- ./suggest/.*
- ./test-framework/.*
- ./tools/.*
- ./tools/forbiddenApis/.*
- ./tools/javadoc/.*
- ./tools/javadoc/junit/.*
- ./tools/junit4/.*
- ./tools/prettify/.*
